import {useState, useRef, useEffect} from "react"; 
import type {NextPage} from 'next';
import Head from 'next/head';
import {Provider} from 'react-redux';
import {store} from "./components/store";
import Image from 'next/image';
import{useForm} from "react-hook-form";
import {motion as m} from "framer-motion";
import Form from './components/Form';
import Calculator from "./components/Calculator";




export default function Home() {
  return (
    <>
      <Head>
        <title>Car Payment App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     <Provider store={store}>  
      <Form /> 
      <Calculator /> 
    </Provider>
      
      
    </> 
  )
}